# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccd8fbc55174689fce86960c6ce8a61067263569ee39090b12aa8439315232101a3512253ee729f947bf4fdb391dca9567bc8962243479c999cac267f65567ea

test:
  secret_key_base: 2a5c350da9fbb2cd069a533e5f4ff3a9980521f5d0a81d475b4e080ba94ea01c29b8a541150a9fa44f15c3d432f669df8aa909df82c4db6e91ab33297256f0af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
